// CONTAINS THE BLOCKS IN THE GAME... USED WHEN LEVEL IS LOADED



// {x: , y: , startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true}, // floor
// {x: 1, y: 4, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true}, // wall (inside)


const hostileGunners = [
    // { x: 12, y: 3.8, facing: 0, shootSpeed: 0.5, health: 4},
    { x: 3, y: 1.8, facing: 1, shootSpeed: 1.5, health: 4},
    { x: 25, y: 12.8, facing: 1, shootSpeed: 1.5, health: 4},
    { x: 15, y: 14.8, facing: 1, shootSpeed: 1.5, health: 4},
    { x: 19, y: 14.8, facing: 1, shootSpeed: 1.5, health: 4},
    { x: 13, y: 18.8, facing: 0, shootSpeed: 1.5, health: 4},
    { x: 5, y: 18.8, facing: 0, shootSpeed: 1.5, health: 4},
    { x: 8, y: 23.8, facing: 0, shootSpeed: 1.5, health: 4},
]; 


const blocks = [
    // up left wall
    {x: 0, y: 0, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},
    {x: 0, y: 1, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},
    {x: 0, y: 2, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},

    // ceiling on right
    {x: 19, y: 0, startRow: 0, startCol: 3, row: 2, col: 0, isCollidable: true},
    {x: 20, y: 0, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 21, y: 0, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 22, y: 0, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 23, y: 0, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 24, y: 0, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 25, y: 0, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 26, y: 0, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 27, y: 0, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 28, y: 0, startRow: 0, startCol: 3, row: 2, col: 2, isCollidable: true},

    // row 3 (main top row)
    {x: 0, y: 3, startRow: 0, startCol: 3, row: 1, col: 3, isCollidable: true},
    {x: 1, y: 3, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 2, y: 3, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 3, y: 3, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 4, y: 3, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 5, y: 3, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 6, y: 3, startRow: 0, startCol: 3, row: 0, col: 2, isCollidable: true},

    // row 4
    {x: 0, y: 4, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 1, y: 4, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 2, y: 4, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 3, y: 4, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 4, y: 4, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 5, y: 4, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 6, y: 4, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},

    // row 5
    {x: 0, y: 5, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 1, y: 5, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 2, y: 5, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 3, y: 5, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 4, y: 5, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 5, y: 5, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 6, y: 5, startRow: 0, startCol: 3, row: 1, col: 3, isCollidable: true},
    {x: 7, y: 5, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 8, y: 5, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 9, y: 5, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 10, y: 5, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 11, y: 5, startRow: 0, startCol: 3, row: 0, col: 2, isCollidable: true},

    {x: 18, y: 5, startRow: 0, startCol: 3, row: 0, col: 0, isCollidable: true},
    {x: 19, y: 5, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 20, y: 5, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 21, y: 5, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 22, y: 5, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 23, y: 5, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 24, y: 5, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 25, y: 5, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 26, y: 5, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 27, y: 5, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 28, y: 5, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 29, y: 5, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 30, y: 5, startRow: 0, startCol: 3, row: 0, col: 2, isCollidable: true},


    // row 6
    {x: 1, y: 6, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 2, y: 6, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 3, y: 6, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 4, y: 6, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 5, y: 6, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 6, y: 6, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 7, y: 6, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 8, y: 6, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 9, y: 6, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 10, y: 6, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 11, y: 6, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},

    {x: 18, y: 6, startRow: 0, startCol: 3, row: 1, col: 0, isCollidable: true},
    {x: 19, y: 6, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 20, y: 6, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 21, y: 6, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 22, y: 6, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 23, y: 6, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 24, y: 6, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 25, y: 6, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 26, y: 6, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 27, y: 6, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 28, y: 6, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 29, y: 6, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 30, y: 6, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},
    

    // row 7
    {x: 1, y: 7, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 2, y: 7, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 3, y: 7, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 4, y: 7, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 5, y: 7, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 6, y: 7, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 7, y: 7, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 8, y: 7, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 9, y: 7, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 10, y: 7, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 11, y: 7, startRow: 0, startCol: 3, row: 1, col: 3, isCollidable: true},
    {x: 12, y: 7, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 13, y: 7, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 14, y: 7, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 15, y: 7, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 16, y: 7, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 17, y: 7, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},

    {x: 18, y: 7, startRow: 0, startCol: 3, row: 1, col: 4, isCollidable: true},
    {x: 19, y: 7, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 20, y: 7, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 21, y: 7, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 22, y: 7, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 23, y: 7, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 24, y: 7, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 25, y: 7, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 26, y: 7, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 27, y: 7, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 28, y: 7, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 29, y: 7, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 30, y: 7, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},

    // row 8
    {x: 1, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 2, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 3, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 4, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 5, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 6, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 7, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 8, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 9, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 10, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 11, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 12, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 13, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 14, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 15, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 16, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 17, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},

    {x: 18, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 19, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 20, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 21, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 22, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 23, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 24, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 25, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 26, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 27, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 28, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 29, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 30, y: 8, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},


    // row 9
    {x: 1, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 2, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 3, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 4, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 5, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 6, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 7, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 8, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 9, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 10, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 11, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 12, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 13, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 14, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 15, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 16, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 17, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 18, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 19, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 20, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 21, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 22, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 23, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 24, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 25, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 26, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 27, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 28, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 29, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 30, y: 9, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},


    // far right wall
    {x: 33, y: 0, startRow: 0, startCol: 3, row: 1, col: 0, isCollidable: true},
    {x: 33, y: 1, startRow: 0, startCol: 3, row: 1, col: 0, isCollidable: true},
    {x: 33, y: 2, startRow: 0, startCol: 3, row: 1, col: 0, isCollidable: true},
    {x: 33, y: 3, startRow: 0, startCol: 3, row: 1, col: 0, isCollidable: true},
    {x: 33, y: 4, startRow: 0, startCol: 3, row: 1, col: 0, isCollidable: true},
    {x: 33, y: 5, startRow: 0, startCol: 3, row: 1, col: 0, isCollidable: true},
    {x: 33, y: 6, startRow: 0, startCol: 3, row: 1, col: 0, isCollidable: true},
    {x: 33, y: 7, startRow: 0, startCol: 3, row: 1, col: 0, isCollidable: true},
    {x: 33, y: 8, startRow: 0, startCol: 3, row: 1, col: 0, isCollidable: true},
    {x: 33, y: 9, startRow: 0, startCol: 3, row: 1, col: 0, isCollidable: true},
    {x: 33, y: 10, startRow: 0, startCol: 3, row: 1, col: 0, isCollidable: true},
    {x: 33, y: 11, startRow: 0, startCol: 3, row: 1, col: 0, isCollidable: true},
    {x: 33, y: 12, startRow: 0, startCol: 3, row: 1, col: 0, isCollidable: true},
    {x: 33, y: 13, startRow: 0, startCol: 3, row: 1, col: 0, isCollidable: true},
    {x: 34, y: 0, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 34, y: 1, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 34, y: 2, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 34, y: 3, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 34, y: 4, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 34, y: 5, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 34, y: 6, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 34, y: 7, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 34, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 34, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 34, y: 10, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 34, y: 11, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 34, y: 12, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 34, y: 13, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 35, y: 0, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 35, y: 1, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 35, y: 2, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 35, y: 3, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 35, y: 4, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 35, y: 5, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 35, y: 6, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 35, y: 7, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 35, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 35, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 35, y: 10, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 35, y: 11, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 35, y: 12, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 35, y: 13, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
   
    
    // row 10: 
    {x: 1, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 2, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 3, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 4, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 5, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 6, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 7, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 8, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 9, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 10, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 11, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 12, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 13, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 14, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 15, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 16, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 17, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},

    {x: 18, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 19, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 20, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 21, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 22, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 23, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 24, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 25, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 26, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 27, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 28, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 29, y: 10, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 30, y: 10, startRow: 0, startCol: 3, row: 2, col: 2, isCollidable: true},


    // row 11
    // row 12
    // row 13
    // row 14
    {x: 25, y: 14, startRow: 0, startCol: 3, row: 0, col: 0, isCollidable: true},
    {x: 26, y: 14, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 27, y: 14, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 28, y: 14, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 29, y: 14, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 30, y: 14, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 31, y: 14, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 32, y: 14, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 33, y: 14, startRow: 0, startCol: 3, row: 1, col: 4, isCollidable: true},
    {x: 34, y: 14, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 35, y: 14, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},

    // row 15
    {x: 25, y: 15, startRow: 0, startCol: 3, row: 1, col: 0, isCollidable: true},
    {x: 26, y: 15, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 27, y: 15, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 28, y: 15, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 29, y: 15, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 30, y: 15, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 31, y: 15, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 32, y: 15, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 33, y: 15, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 34, y: 15, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 35, y: 15, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},

    // row 16
    {x: 15, y: 16, startRow: 0, startCol: 3, row: 0, col: 0, isCollidable: true},
    {x: 16, y: 16, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 17, y: 16, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 18, y: 16, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 19, y: 16, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 20, y: 16, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 21, y: 16, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 22, y: 16, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 23, y: 16, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 24, y: 16, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 25, y: 16, startRow: 0, startCol: 3, row: 1, col: 4, isCollidable: true},
    {x: 26, y: 16, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 27, y: 16, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 28, y: 16, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 29, y: 16, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 30, y: 16, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 31, y: 16, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 32, y: 16, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 33, y: 16, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 34, y: 16, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 35, y: 16, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},

    // row 17
    {x: 15, y: 17, startRow: 0, startCol: 3, row: 1, col: 0, isCollidable: true},
    {x: 16, y: 17, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 17, y: 17, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 18, y: 17, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 19, y: 17, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 20, y: 17, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 21, y: 17, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 22, y: 17, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 23, y: 17, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 24, y: 17, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 25, y: 17, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 26, y: 17, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 27, y: 17, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 28, y: 17, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 29, y: 17, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 30, y: 17, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 31, y: 17, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 32, y: 17, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 33, y: 17, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 34, y: 17, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 35, y: 17, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},

    // row 18
    {x: 15, y: 18, startRow: 0, startCol: 3, row: 1, col: 0, isCollidable: true},
    {x: 16, y: 18, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 17, y: 18, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 18, y: 18, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 19, y: 18, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 20, y: 18, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 21, y: 18, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 22, y: 18, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 23, y: 18, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 24, y: 18, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 25, y: 18, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 26, y: 18, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 27, y: 18, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 28, y: 18, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 29, y: 18, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 30, y: 18, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 31, y: 18, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 32, y: 18, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 33, y: 18, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 34, y: 18, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 35, y: 18, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},

    // row 19
    {x: 15, y: 19, startRow: 0, startCol: 3, row: 1, col: 0, isCollidable: true},
    {x: 16, y: 19, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 17, y: 19, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 18, y: 19, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 19, y: 19, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 20, y: 19, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 21, y: 19, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 22, y: 19, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 23, y: 19, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 24, y: 19, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 25, y: 19, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 26, y: 19, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 27, y: 19, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 28, y: 19, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 29, y: 19, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 30, y: 19, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 31, y: 19, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 32, y: 19, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 33, y: 19, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 34, y: 19, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 35, y: 19, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},

    // row 20

    {x: 0, y: 20, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},
    {x: 5, y: 20, startRow: 0, startCol: 3, row: 0, col: 0, isCollidable: true},
    {x: 6, y: 20, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 7, y: 20, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 8, y: 20, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 9, y: 20, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 10, y: 20, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 11, y: 20, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 12, y: 20, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 13, y: 20, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 14, y: 20, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 15, y: 20, startRow: 0, startCol: 3, row: 1, col: 4, isCollidable: true},
    {x: 16, y: 20, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 17, y: 20, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},

    {x: 18, y: 20, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 19, y: 20, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 20, y: 20, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 21, y: 20, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 22, y: 20, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 23, y: 20, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 24, y: 20, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 25, y: 20, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 26, y: 20, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 27, y: 20, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 28, y: 20, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 29, y: 20, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 30, y: 20, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},


    // row 21
    {x: 5, y: 21, startRow: 0, startCol: 3, row: 2, col: 0, isCollidable: true},
    {x: 6, y: 21, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 7, y: 21, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 8, y: 21, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 9, y: 21, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 10, y: 21, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 11, y: 21, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 12, y: 21, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 13, y: 21, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 14, y: 21, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 15, y: 21, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 16, y: 21, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 17, y: 21, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 18, y: 21, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 19, y: 21, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 20, y: 21, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 21, y: 21, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 22, y: 21, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 23, y: 21, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 24, y: 21, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 25, y: 21, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 26, y: 21, startRow: 0, startCol: 3, row: 2, col: 1, isCollidable: true},
    {x: 27, y: 21, startRow: 0, startCol: 3, row: 0, col: 4, isCollidable: true},
    {x: 28, y: 21, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 29, y: 21, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 30, y: 21, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},

    // left wall in mid corridor
    {x: 0, y: 6, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 0, y: 7, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 0, y: 8, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 0, y: 9, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 0, y: 10, startRow: 0, startCol: 3, row: 0, col: 3, isCollidable: true},
    {x: 0, y: 11, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},
    {x: 0, y: 12, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},
    {x: 0, y: 13, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},
    {x: 0, y: 14, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},
    {x: 0, y: 15, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},
    {x: 0, y: 16, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},
    {x: 0, y: 17, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},
    {x: 0, y: 18, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},
    {x: 0, y: 19, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},

    {x: 0, y: 21, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},
    {x: 0, y: 22, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},
    {x: 0, y: 23, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},
    {x: 0, y: 24, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},
    {x: 0, y: 25, startRow: 0, startCol: 3, row: 1, col: 3, isCollidable: true},
    {x: 0, y: 26, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},
    {x: 0, y: 27, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},
    {x: 0, y: 28, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},

    // row 25
    {x: 1, y: 25, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 2, y: 25, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 3, y: 25, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 4, y: 25, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 5, y: 25, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 6, y: 25, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 7, y: 25, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 8, y: 25, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 9, y: 25, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 10, y: 25, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 11, y: 25, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 12, y: 25, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 13, y: 25, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 14, y: 25, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 15, y: 25, startRow: 0, startCol: 3, row: 0, col: 2, isCollidable: true},

    // row 26
    {x: 1, y: 26, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 2, y: 26, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 3, y: 26, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 4, y: 26, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 5, y: 26, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 6, y: 26, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 7, y: 26, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 8, y: 26, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 9, y: 26, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 10, y: 26, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 11, y: 26, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 12, y: 26, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 13, y: 26, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 14, y: 26, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 15, y: 26, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},

    // row 27
    {x: 1, y: 27, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 2, y: 27, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 3, y: 27, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 4, y: 27, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 5, y: 27, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 6, y: 27, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 7, y: 27, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 8, y: 27, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 9, y: 27, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 10, y: 27, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 11, y: 27, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 12, y: 27, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 13, y: 27, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 14, y: 27, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 15, y: 27, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},

    // row 28
    {x: 1, y: 28, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 2, y: 28, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 3, y: 28, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 4, y: 28, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 5, y: 28, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 6, y: 28, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 7, y: 28, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 8, y: 28, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 9, y: 28, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 10, y: 28, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 11, y: 28, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 12, y: 28, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 13, y: 28, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 14, y: 28, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 15, y: 28, startRow: 0, startCol: 3, row: 1, col: 3, isCollidable: true},
    {x: 16, y: 28, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 17, y: 28, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 18, y: 28, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 19, y: 28, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 20, y: 28, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 21, y: 28, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 22, y: 28, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 23, y: 28, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 24, y: 28, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 25, y: 28, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 26, y: 28, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    {x: 27, y: 28, startRow: 0, startCol: 3, row: 1, col: 4, isCollidable: true},
    {x: 28, y: 28, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 29, y: 28, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 30, y: 28, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},

    // row 29
    {x: 1, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 2, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 3, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 4, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 5, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 6, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 7, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 8, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 9, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 10, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 11, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 12, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 13, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 14, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 15, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 16, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 17, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 18, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 19, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 20, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 21, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 22, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 23, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 24, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 25, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 26, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 27, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 28, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 29, y: 29, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 30, y: 29, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},

    // row 30
    {x: 1, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 2, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 3, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 4, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 5, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 6, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 7, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 8, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 9, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 10, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 11, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 12, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 13, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 14, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 15, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 16, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 17, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 18, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 19, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 20, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 21, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 22, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 23, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 24, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 25, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 26, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 27, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 28, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 29, y: 30, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 30, y: 30, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},

    // row 31
    {x: 1, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 2, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 3, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 4, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 5, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 6, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 7, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 8, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 9, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 10, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 11, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 12, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 13, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 14, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 15, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 16, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 17, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 18, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 19, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 20, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 21, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 22, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 23, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 24, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 25, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 26, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 27, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 28, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 29, y: 31, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 30, y: 31, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},

    // row 31
    {x: 1, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 2, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 3, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 4, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 5, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 6, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 7, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 8, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 9, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 10, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 11, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 12, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 13, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 14, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 15, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 16, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 17, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 18, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 19, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 20, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 21, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 22, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 23, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 24, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 25, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 26, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 27, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 28, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 29, y: 32, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 30, y: 32, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},


    // right walls near boss
    {x: 27, y: 22, startRow: 0, startCol: 3, row: 1, col: 0, isCollidable: true},
    {x: 27, y: 23, startRow: 0, startCol: 3, row: 1, col: 0, isCollidable: true},
    {x: 27, y: 24, startRow: 0, startCol: 3, row: 1, col: 0, isCollidable: true},
    {x: 27, y: 25, startRow: 0, startCol: 3, row: 1, col: 0, isCollidable: true},
    {x: 27, y: 26, startRow: 0, startCol: 3, row: 1, col: 0, isCollidable: true},
    {x: 27, y: 27, startRow: 0, startCol: 3, row: 1, col: 0, isCollidable: true},
    {x: 27, y: 28, startRow: 0, startCol: 3, row: 1, col: 0, isCollidable: true},

    {x: 28, y: 22, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 28, y: 23, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 28, y: 24, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 28, y: 25, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 28, y: 26, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 28, y: 27, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 28, y: 28, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    
    {x: 29, y: 22, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 29, y: 23, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 29, y: 24, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 29, y: 25, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 29, y: 26, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 29, y: 27, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 29, y: 28, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},

    {x: 30, y: 22, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 30, y: 23, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 30, y: 24, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 30, y: 25, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 30, y: 26, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 30, y: 27, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    {x: 30, y: 28, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},

    
    // {x: 16, y: 25, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    // {x: 17, y: 25, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    // {x: 18, y: 25, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    // {x: 19, y: 25, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    // {x: 20, y: 25, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    // {x: 21, y: 25, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    // {x: 22, y: 25, startRow: 0, startCol: 3, row: 0, col: 1, isCollidable: true},
    // {x: 23, y: 25, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 24, y: 25, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 25, y: 25, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 26, y: 25, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 27, y: 25, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 28, y: 25, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 29, y: 25, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 30, y: 25, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},

    // {x: 1, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 2, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 3, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 4, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 5, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 6, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 7, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 8, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 9, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 10, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 11, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 12, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 13, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 14, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 15, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 16, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 17, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 18, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 19, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 20, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 21, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 22, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 23, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 24, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 25, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 26, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 27, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 28, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 29, y: rowww, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: 30, y: rowww, startRow: 0, startCol: 3, row: 1, col: 2, isCollidable: true},

    // {x: , y: 5, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: , y: 5, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    // {x: , y: 5, startRow: 0, startCol: 3, row: 1, col: 1, isCollidable: true},
    

   

];


const hammers = [
    // {x: 12, y: 1},
    {x: 20, y: 1},
    {x: 24, y: 1},
    {x: 26, y: 1},

];

const transporters = [
    // {x: 17, y: 6, w: 2, movingRight: true},
    {x: 13.5, y: 5, w: 2, movingRight: true},
    {x: 11, y: 16, w: 2, movingRight: false},
    {x: 6, y: 16, w: 2, movingRight: true},
    {x: 2.25, y: 18, w: 0, movingRight: true},
];





const cashLocals = [
    {x: 2.25, y: 2.25},
    {x: 2.75, y: 2.25},
    {x: 3.75, y: 2.25},
    {x: 3.75, y: 2.25},
    {x: 2.5, y: 1.75},
    {x: 3, y: 1.75},
    {x: 3.5, y: 1.75},

    {x: 7.25, y: 3},
    {x: 7.25, y: 3.5},
    {x: 7.25, y: 4},
    

    {x: 7.25, y: 4.5},
    {x: 7.75, y: 4.5},
    
    
    {x: 11.5, y: 4.25},


    {x: 13.5, y: 6.25},
    {x: 14, y: 6.25},
    {x: 14.5, y: 6.25},
    {x: 15, y: 6.25},
    {x: 15.5, y: 6.25},
    {x: 16, y: 6.25},
    
    {x: 22.25, y: 4.25},
    {x: 23.25, y: 4.25},
    
    {x: 9.5, y: 13},
    {x: 9.5, y: 13.5},
    {x: 9.5, y: 14},
    
    {x: 9, y: 19},
    {x: 9.5, y: 19},
    {x: 10, y: 19},
    {x: 10.5, y: 19},


    {x: 14, y: 16},
    {x: 14, y: 16.5},
    {x: 14, y: 17},
    {x: 14, y: 17.5},
    {x: 14, y: 18},

    {x: 9.5, y: 16},
    {x: 9.5, y: 16.5},
    {x: 9.5, y: 17},
    {x: 9.5, y: 17.5},
    {x: 9.5, y: 18},

    {x: 21.5, y: 15},
    {x: 22, y: 15},
    {x: 22.5, y: 15},
    {x: 23, y: 15},
    {x: 21.75, y: 14.25},
    {x: 22.75, y: 14.25},
    {x: 22.25, y: 14.25},

    {x: 2, y: 21},
    {x: 3.5, y: 21},
    {x: 2, y: 21.5},
    {x: 3.5, y: 21.5},
    {x: 2, y: 22},
    {x: 3.5, y: 22},
    {x: 2, y: 22.5},
    {x: 3.5, y: 22.5},
    {x: 2, y: 23},
    {x: 3.5, y: 23},
    {x: 2, y: 23.5},
    {x: 3.5, y: 23.5},



    // {x: , y: },
    // {x: , y: },
    // {x: , y: },
    // {x: , y: },
    // {x: , y: },
];